version: 0.2
phases:
  install:
    commands:
      - aws --version
  build:
    commands:
      - |
        echo "Syncing site to s3://$APP_BUCKET"
        aws s3 sync . "s3://$APP_BUCKET" --delete           --exclude ".git/*" --exclude ".github/*"           --exclude "README.md" --exclude "LICENSE"           --exclude "buildspec.yml"
artifacts:
  files:
    - '**/*'
